---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-operator-webui
  namespace: flink
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flink-operator-webui
rules:
- apiGroups: ["flink.apache.org"]
  resources: ["flinkdeployments"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: ["flink.apache.org"]
  resources: ["flinkdeployments/status"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-operator-webui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flink-operator-webui
subjects:
- kind: ServiceAccount
  name: flink-operator-webui
  namespace: flink
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-operator-webui
  namespace: flink
  labels:
    app: flink-operator-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-operator-webui
  template:
    metadata:
      labels:
        app: flink-operator-webui
    spec:
      serviceAccountName: flink-operator-webui
      containers:
      - name: webui
        # Replace with your actual container registry and image tag
        # Example: image: ghcr.io/your-org/flink-operator-webui:v1.0.0
        image: your-registry/flink-operator-webui:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flink-operator-webui
  namespace: flink
  labels:
    app: flink-operator-webui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: flink-operator-webui
